version: '2'

networks:
  proxy:
    external:
      name: proxy

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8084:80"
    expose:
      - "80"
    volumes:
      - .:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: aliceperformance.com,www.aliceperformance.com
      LETSENCRYPT_HOST: aliceperformance.com,www.aliceperformance.com
      LETSENCRYPT_EMAIL: davidjonasdesign@gmail.com
    networks:
      - default
      - proxy
